based_on_package: "ur_mock"

# [Required]
hardware:
  # Set simulated to false if you are using this as a configuration for real hardware.
  # This allows users to switch between mock and real hardware by changing a single parameter with config inheritance.
  # [Required]
  simulated: False

  # Specify additional launch files for running the robot with real hardware.
  # [Optional, defaults to a blank launch file if not specified]
  robot_driver_persist_launch_file:
    package: "ur_hw"
    path: "launch/robot_drivers_to_persist.launch.py"

  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    urdf_params:
      - name: "ur3e"
      # NOTE: If using a different UR model, update type here and joint limits in the config/moveit/joint_limits.yaml file.
      # possible 'ur_type' values: ur3, ur3e, ur5, ur5e, ur10, ur10e, ur16e, ur20, ur30
      - ur_type: "ur3e"
      - use_fake_hardware: "false"
      - robot_ip: "0.0.0.0"
      - headless_mode: "true"
      - use_tool_communication: "true"
      - tool_voltage: "24"
      - joint_limit_parameters_file:
          package: "ur_hw"
          path: "config/moveit/joint_limits.yaml"

# Configuration files for MoveIt.
# For more information, refer to https://moveit.picknik.ai/main/doc/how_to_guides/moveit_configuration/moveit_configuration_tutorial.html
# [Required]
moveit_params:
  joint_limits:
    package: "ur_hw"
    path: "config/moveit/joint_limits.yaml"
  servo_joint_limits:
    package: "ur_hw"
    path: "config/moveit/hard_joint_limits.yaml"
