# [Required]
hardware:
  # Set simulated to false if you are using this as a configuration for real hardware.
  # This allows users to switch between mock and real hardware by changing a single parameter with config inheritance.
  # [Required]
  simulated: True

  # If the MoveIt Pro Agent should launch the ros2 controller node.
  # [Optional, default=True]
  launch_control_node: True

  # If the MoveIt Pro Agent should launch the robot state publisher.
  # This should be false if you are launching the robot state publisher as part of drivers.
  # [Optional, default=True]
  launch_robot_state_publisher: True

  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    urdf:
      package: "ur_mock_config"
      path: "description/picknik_ur.xacro"
    srdf:
      package: "ur_mock_config"
      path: "config/moveit/picknik_ur.srdf"
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the UR descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
      - name: "ur10e"
      # NOTE: If using a different UR model, update type here and joint limits in the config/moveit/joint_limits.yaml file.
      # possible 'ur_type' values: ur3, ur3e, ur5, ur5e, ur10, ur10e, ur16e, ur20, ur30
      - ur_type: "ur10e"
      - use_fake_hardware: "true"
      - robot_ip: "0.0.0.0"
      - headless_mode: "true"
      - use_tool_communication: "true"
      - tool_voltage: "24"
      - joint_limit_parameters_file:
          package: "ur_mock_config"
          path: "config/moveit/joint_limits.yaml"

# Configuration files for MoveIt.
# For more information, refer to https://moveit.picknik.ai/main/doc/how_to_guides/moveit_configuration/moveit_configuration_tutorial.html
# [Required]
moveit_params:
  # Used by the Waypoint Manager to save joint states from this joint group.
  joint_group_name: "manipulator"

  ompl_planning:
    package: "ur_mock_config"
    path: "config/moveit/ompl_planning.yaml"
  kinematics:
    package: "ur_mock_config"
    path: "config/moveit/pose_ik_distance.yaml"
  servo:
    package: "ur_mock_config"
    path: "config/moveit/ur_servo.yaml"
  sensors_3d:
    package: "ur_mock_config"
    path: "config/moveit/sensors_3d.yaml"
  joint_limits:
    package: "ur_mock_config"
    path: "config/moveit/joint_limits.yaml"
  servo_joint_limits:
    package: "ur_mock_config"
    path: "config/moveit/hard_joint_limits.yaml"
  pose_jog:
    package: "ur_mock_config"
    path: "config/moveit/pose_jog.yaml"

  publish:
    planning_scene: True
    geometry_updates: True
    state_updates: True
    transforms_updates: True

  trajectory_execution:
    manage_controllers: True
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
      - "moveit_studio::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_studio::behaviors::ServoBehaviorsLoader"
      - "moveit_studio::behaviors::VisionBehaviorsLoader"
      - "moveit_studio::behaviors::ConverterBehaviorsLoader"
    trigger_pstop_reset_service:
      - "trigger_pstop_reset_service::TriggerPStopResetServiceBehaviorsLoader"
  objective_library_paths:
    # You must use a unique key for each package.
    core_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/core"
    motion_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/motion"
    perception_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/perception"
    ur_mock_objectives:
      package_name: "ur_mock_config"
      relative_path: "objectives"
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "ur_mock_config"
    relative_path: "waypoints/ur_waypoints.yaml"

# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  config:
    package: "ur_mock_config"
    path: "config/control/picknik_ur.ros2_control.yaml"
  # MoveIt Pro will load and activate these controllers at start up to ensure they are available.
  # If not specified, it is up to the user to ensure the appropriate controllers are active and available
  # for running the application.
  # [Optional, default=[]]
  controllers_active_at_startup:
    - "force_torque_sensor_broadcaster"
    - "robotiq_gripper_controller"
    - "joint_state_broadcaster"
    - "servo_controller"
    - "io_and_status_controller"
    - "robotiq_activation_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  # [Optional, default=[]]
  controllers_inactive_at_startup:
    - "joint_trajectory_controller"
    - "joint_trajectory_admittance_controller"
    - "velocity_force_controller"
  # Any controllers here will not be spawned by MoveIt Pro.
  # [Optional, default=[]]
  controllers_not_managed: []
  # Optionally configure remapping rules to let multiple controllers receive commands on the same topic.
  # [Optional, default=[]]
  controller_shared_topics: []
