#
#  Site config for Dev-009 UR5e + EPick gripper
#  Based on ur_hw (which inherits from ur_mock)
#

# Inherit from ur_hw
based_on_package: "ur_hw"

hardware:
  simulated: true

  robot_driver_persist_launch_file:
    package: "ur_hw"
    path: "launch/robot_drivers_to_persist.launch.py"

  robot_description:
    urdf:
      package: "picknik_009_ur5e_config"
      path: "description/picknik_009_ur5e.urdf.xacro"
    srdf:
      package: "picknik_009_ur5e_config"
      path: "config/moveit/picknik_009_ur5e.srdf"
    urdf_params:
      - use_fake_hardware: "true"
      - robot_ip: "0.0.0.0"

objectives:
  behavior_loader_plugins:
    core:
      - "moveit_pro::behaviors::CoreBehaviorsLoader"
      - "moveit_pro::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_pro::behaviors::VisionBehaviorsLoader"
      - "moveit_pro::behaviors::ConverterBehaviorsLoader"

# Use our own ros2_control config with EPick controller instead of Robotiq 2F-85
ros2_control:
  config:
    package: "picknik_009_ur5e_config"
    path: "config/control/picknik_ur.ros2_control.yaml"
  controllers_active_at_startup:
    - "force_torque_sensor_broadcaster"
    - "joint_state_broadcaster"
  controllers_inactive_at_startup:
    - "joint_trajectory_controller"
    - "joint_trajectory_admittance_controller"
    - "velocity_force_controller"
    - "joint_velocity_controller"
  controllers_not_managed: []
  controller_shared_topics: []
